
package com.xlx.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BMWCar", targetNamespace = "http://ws.xlx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BMWCar {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarName", targetNamespace = "http://ws.xlx.com/", className = "com.xlx.ws.client.GetCarName")
    @ResponseWrapper(localName = "getCarNameResponse", targetNamespace = "http://ws.xlx.com/", className = "com.xlx.ws.client.GetCarNameResponse")
    @Action(input = "http://ws.xlx.com/BMWCar/getCarNameRequest", output = "http://ws.xlx.com/BMWCar/getCarNameResponse")
    public String getCarName();

}
